- Saudox/app/Http/Controllers/Auth/LoginController.php
- Saudox/app/Http/Controllers/Profissional/Auth/LoginController.php
- Saudox/public/css/main.css
- Saudox/public/css/refator.css
- Saudox/resources/views/auth/login.blade.php
- Saudox/resources/views/layouts/mainlayout.blade.php
- Saudox/resources/views/profissional/admin/home.blade.php
Os commits estão bem separadinhos e dá pra saber o que foi feito certinho.
Mais ajustes devem ser feitos no futuro (outros pull requests)
> Pequenos ajustes em algumas partes das views

- Saudox/app/Http/Controllers/Profissional/ProfissionalController.php
- Saudox/app/Profissional.php
- Saudox/database/migrations/2020_05_13_000002_create_profissionals_table.php
- Saudox/resources/views/auth/login.blade.php
- Saudox/resources/views/profissional/admin/editar_profissional.blade.php
- Saudox/resources/views/profissional/ver_profissional.blade.php
- Saudox/routes/profissional/profissional.php
On branch dev
Changes to be committed:
modified:   app/Http/Controllers/Profissional/ProfissionalController.php
modified:   app/Profissional.php
modified:   database/migrations/2020_05_13_000002_create_profissionals_table.php
modified:   resources/views/auth/login.blade.php
modified:   resources/views/profissional/admin/editar_profissional.blade.php
modified:   resources/views/profissional/ver_profissional.blade.php
modified:   routes/profissional/profissional.php
> Aviso do profissional e pequeno erro na view de login

- Saudox/app/Agendamentos.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalController.php
- Saudox/composer.lock
- Saudox/database/factories/AgendamentosFactory.php
- Saudox/phpunit.xml
- Saudox/resources/views/profissional/agendar.blade.php
- Saudox/resources/views/profissional/criar_paciente.blade.php
- Saudox/resources/views/profissional/editar_agendamento.blade.php
- Saudox/resources/views/profissional/home.blade.php
- Saudox/resources/views/profissional/ver_agendamento.blade.php
- Saudox/routes/profissional/profissional.php
- Saudox/tests/Feature/AnamneseTest.php
- Saudox/tests/Feature/AvaliacaoTest.php
- Saudox/tests/Feature/CadastroClienteTest.php
- Saudox/tests/Feature/CadastroProfissionalTest.php
- Saudox/tests/Feature/EvolucaoTest.php
- Saudox/tests/Feature/LoginPacienteTest.php
- Saudox/tests/Feature/LoginProfissionalTest.php
- Saudox/tests/Feature/RotasTest.php
- Saudox/tests/TestCase.php
- Saudox/tests/Unit/AdminControllerTest.php
- Estava sendo mostrado agendamentos concluídos/cancelados na home do profissional
- O agendamento está sendo usado como base para completar o cadastro do paciente
- Desligando testes desnecessários
- Reescrevendo alguns testes
- Testes de cadastro de profissional ok (tinha problemas na criação do profissional que se ia logar)
- Testes de cadastro de paciente ainda faltam serem reescritos
> Alguns ajustes da ultima release

- Saudox/app/Http/Controllers/Controller.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalController.php
- Saudox/app/Profissional.php
- Saudox/database/factories/ProfissionalFactory.php
- Saudox/database/seeds/ProfissionaisAutSeeds.php
- Saudox/public/css/main.css
- Saudox/public/css/refator.css
- Saudox/resources/views/profissional/admin/criar_profissional.blade.php
- Saudox/resources/views/profissional/admin/editar_profissional.blade.php
- Saudox/resources/views/profissional/home.blade.php
- Saudox/tests/Feature/CadastroClienteTest.php
- Saudox/tests/Feature/CadastroProfissionalTest.php
- Redução das profissões em array
- Melhoras de código no lugar errado nos controllers
- Pequenos bugs e ajustes
> Finalmente todos os testes passam

- Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/criar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/editar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/ver.blade.php
- Saudox/routes/profissional/anamnese/terapia_ocupacional.php
- Tela, método do controller e rota de edição de anamnese terapia ocupacional
- Resolução de alguns problemas (Ex: Uso de isset)
> Edição da anamnese terapia ocupacional + resolução de bugs menores

- Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
- Saudox/app/Profissional.php
- Saudox/public/css/refator.css
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/criar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/ver.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Botão de criação/visualização de anamnese na pagina do perfil do paciente
- Entregando id do profissional na hora da criação da anamnese
> Alguns ajustes no controller de anamnese e botões no perfil do paciente

- Saudox/tests/Feature/AgendamentosTest.php
Testes de validar: datas, horários, email e telefone
> Testes de validação

- Saudox/app/AvaliacaoJudo.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
- Saudox/app/Profissional.php
- Saudox/resources/views/profissional/avaliacao/judo/criar.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Saudox/routes/profissional/avaliacao/judo.php
- Criação da view de criar avaliação
- Método no controller
- Rotas
- Regras de validação
- Fillable do model
(Tudo em cima da esteira :sunglasses: )
> Criação da avaliação de judo apenas

- Saudox/app/Http/Controllers/PacienteController.php
- Saudox/public/css/main.css
- Saudox/public/css/refator.css
- Saudox/resources/views/paciente/home.blade.php
- Saudox/resources/views/profissional/home.blade.php
- Adicionando a home do paciente, preciso de opiniões sobre o que mudar... Tô achando feia, porém pode ser só eu né
> [#174982748] Home de paciente pronta, mas feia

- Saudox/resources/views/layouts/mainlayout.blade.php
- Saudox/resources/views/paciente/home.blade.php
- Ajustando espaçamento
- Ajustando visibilidade de botões e labels
- Ajustando posição de alguns campos
> [#174982748] Refinando algumas coisas na home de paciente

- Saudox/tests/Feature/AnamneseTerapiaOTest.php
- Saudox/tests/Feature/AnamneseTest.php
- Comentando a parte do teste que possui o bug da view
> Evitando bug no teste (old_checked)

- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
- Saudox/database/factories/Anamnese_Terapia_OcupacionalFactory.php
- Saudox/database/factories/Anamnese_fonoaudiologiaFactory.php
- Saudox/database/factories/Avaliacao_JudoFactory.php
- Saudox/tests/Unit/AnamneseFonoTest.php
- Saudox/tests/Unit/AnamneseTOTest.php
- Saudox/tests/Unit/AvaliacaoJudoTest.php
- Avaliação de judô
- Anamnese de Fono
- Anamnese de Terapia Ocupacional
modified:   app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
modified:   database/factories/Anamnese_Terapia_OcupacionalFactory.php
modified:   database/factories/Anamnese_fonoaudiologiaFactory.php
modified:   database/factories/Avaliacao_JudoFactory.php
new file:   tests/Unit/AnamneseFonoTest.php
new file:   tests/Unit/AnamneseTOTest.php
new file:   tests/Unit/AvaliacaoJudoTest.php
> Testes unitários

- Saudox/database/factories/ProfissionalFactory.php
- Saudox/tests/Feature/AnamneseFonoTest.php
- Saudox/tests/Feature/AnamneseTerapiaOTest.php
- Saudox/tests/Feature/AvaliacaoJudoTest.php
- Saudox/tests/Feature/AvaliacaoTest.php
- Saudox/tests/Feature/PacienteHomeTest.php
- Testes de Avaliação Judô (criar e ver avaliação)
- Organizando sistema de senha dentro dos arquivos de teste
- Factory de profissional ajustado
> [#174990377] Testes de Avaliação Judô + Organização de Código

- Saudox/app/Http/Controllers/PacienteAvaliacaoController.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
- Saudox/public/css/main.css
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/ver.blade.php
- Tela de visualização de terapia ocupacional (Profissional)
- Adicionei duas classes bem úteis em CSS para poder lidar com campos "grandes"
> [#174990369] Ver avaliação terapia ocupacional

- Saudox/public/css/main.css
- Saudox/public/css/refator.css
- Saudox/resources/views/paciente/home.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Saudox/resources/views/profissional/ver_profissional.blade.php
- Melhorando visualização das telas:
#Home paciente
#Ver perfil de paciente
#Ver perfil de profissional
> Melhorias de visualização de telas importantes

- Saudox/resources/views/profissional/anamnese/fonoaudiologia/criar.blade.php
- Saudox/resources/views/profissional/anamnese/fonoaudiologia/editar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/criar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/editar.blade.php
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/criar.blade.php
- Saudox/tests/Feature/AnamneseFonoTest.php
- Saudox/tests/Feature/AnamneseTerapiaOTest.php
- Saudox/tests/Feature/AvaliacaoTerapiaOTest.php
[#174881458] - Resolução temporária do bug da máquina virtual do php
[#174990139] - Resolução temporária do bug da máquina virtual do php
[#174990369] - Implentação dos testes de Anamnese Terapia Ocupacional
> Resolução Temporária do Bug da VM do php + Teste de AnamTO [#174881458][#174990139][#174990369]

- Saudox/app/ajudadores.php
- Saudox/composer.json
- Saudox/resources/views/profissional/anamnese/fonoaudiologia/criar.blade.php
- Saudox/resources/views/profissional/anamnese/fonoaudiologia/editar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/criar.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/editar.blade.php
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/criar.blade.php
- Implementação de funções globais (como helpers)
- Remoção das funções antigas
- Testes passando 😚
On branch olds
Changes to be committed:
new file:   app/ajudadores.php
modified:   composer.json
modified:   resources/views/profissional/anamnese/fonoaudiologia/criar.blade.php
modified:   resources/views/profissional/anamnese/fonoaudiologia/editar.blade.php
modified:   resources/views/profissional/anamnese/terapia_ocupacional/criar.blade.php
modified:   resources/views/profissional/anamnese/terapia_ocupacional/editar.blade.php
modified:   resources/views/profissional/avaliacao/terapia_ocupacional/criar.blade.php
> Mudando função old das views pra uma global

- Saudox/app/AvaliacaoTerapiaOcupacional.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/criar.blade.php
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/editar.blade.php
- Saudox/routes/profissional/avaliacao/terapia_ocupacional.php
- Edição da avaliação de terapia ocupacional
- Mudei a forma como a data era adquirida na tela de criação
> [#174990139] Editar avaliação terapia ocupacional

- Saudox/app/Http/Controllers/HomeController.php
- Saudox/resources/views/layouts/mainlayout.blade.php
- Saudox/resources/views/profissional/home.blade.php
- Retirando o acesso da página "welcome" de usuários logados, agora é necessário deslogar ou não estar logado para acessá-la
- Adicionei o "favicon", que seria o ícone das tabs do navegador :3
> [#175204702] Resolvendo "bug" da navbar

- Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
Não usei o redirect()->back(), já que a anamnese existindo, a única
forma de chegar no formulário é editando a url, e quem for fazer isso já
faz com más intenções, então deixa a pessoa ter o trabalho de preencher
e perder todo esse trabalho. A gente não precisa se importar com a
usabilidade de quem quer usar o sistema errado.
On branch multiplas_criacoes_ana_ava
Changes to be committed:
modified:   app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
modified:   app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
> Verificando já existência de avaliações e anamneses

- Saudox/app/Agendamentos.php
- Saudox/app/Paciente.php
- Saudox/public/css/refator.css
- Saudox/resources/views/profissional/ver_agendamento.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Ajustei o formato de saída das datas de agendamento (Data entrada, saída, nascimento do paciente)
- Mudei o formato de saída da data de nascimento do paciente também
- Tela de visualização de agendamento foi melhorada
- Tela de visualização do perfil de paciente foi beeeeeeeeem melhorada
#Adicionei "nav-bars" para organizar os botões de anamnese, avaliação e já deixei pra os de evolução tbm
#Separei os divs: Div de informação de tela, divs com as "nav-bars", div com o perfil
> [#175204702] Ajustes de formatação das datas + Embelezando/organizando views

- Saudox/app/Agendamentos.php
- Saudox/public/css/refator.css
- Saudox/public/js/main.js
- Saudox/resources/views/auth/login.blade.php
- Saudox/resources/views/layouts/mainlayout.blade.php
- Saudox/resources/views/profissional/home.blade.php
Fiz o rodapé do site, peguei um layout pronto e adaptei. O layout é grátis, então está tudo tranquilo.
Aproveitei pra mandar uns ajustes menores que faltaram em outros pull's (como o espaçamento na home do profissional), mas são só besteirinhas
> Rodapé do site (Extra da entrega 5)

- Saudox/public/css/main.css
- Saudox/resources/lang/en/auth.php
- Saudox/resources/views/auth/login.blade.php
Ajustando em questão de clareza e de estética
As mensagens agora estão traduzidas e aparecem da forma correta ao ocorrer um erro!
> [#175204702] Ajustando mensagens de erro na tela de login

- Saudox/app/Http/Controllers/Profissional/ProfissionalController.php
- Saudox/public/css/main.css
- Saudox/resources/views/profissional/criar_paciente.blade.php
- Saudox/tests/Feature/CadastroClienteTest.php
- Bug da data de nascimento
- Old
- Ajustes na ordem do controller
> Resolvendo bug da criação de paciente da data de nascimento

- Saudox/database/seeds/AgendamentosAutSeeds.php
- Saudox/database/seeds/ConveniosAutSeeds.php
- Saudox/database/seeds/EnderecosAutSeeder.php
- Saudox/database/seeds/PacientesAutSeeder.php
- Saudox/database/seeds/ProfissionaisAutSeeds.php
- Saudox/tests/Feature/AnamneseTerapiaOTest.php
- Saudox/tests/Feature/AvaliacaoJudoTest.php
-Popular BD com dados reais: AgendamentosAutSeeds; EnderecosAutSeeder; ProfissionaisAutSeeds; PacientesAutSeeds; ConveniosAutSeeds
-Testes avaliação judô
-Testes anamnese terapia ocupacional
> Correções pr #88 e #75

- Saudox/database/seeds/PacientesAutSeeder.php
Era removido da lista de irmãos a virgula e o espaço apos TODOS os
nomes, sendo que era necessário remover apenas do ultimo. @ednaldoj
> Resolvendo pequeno bug da seed de paciente

- Saudox/app/AvaliacaoNeuropsicologica.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
- Saudox/database/migrations/2020_05_13_000020_create_avaliacao__neuropsicologicas_table.php
- Saudox/database/seeds/AvaliacaoNeuropsicologicasAutSeeds.php
- Saudox/public/css/tabela.css
- Saudox/public/js/tabela.js
- Saudox/resources/views/profissional/avaliacao/neuropsicologia/criar.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Saudox/routes/profissional/avaliacao/neuropsicologia.php
Alguns ajustes necessários nas migrations e model
> Criação da avaliação neuropsicológica

- Saudox/database/factories/Avaliacao_NeuropsicologicaFactory.php
- Saudox/tests/Feature/AnamnesePNPTest.php
- Saudox/tests/Feature/AvaliacaoNeuropsicologicaTest.php
- teste de criação de avaliação de neuropsicologia
> [#174639133] teste de criação de avaliação de neuropsicologia

- Saudox/tests/Feature/AvaliacaoNeuropsicologicaTest.php
- Teste para visualizar informações de ava. neuro.
> [#174639133] Teste de visualização de ava. neuro.

- Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/ver.blade.php
- Saudox/resources/views/profissional/avaliacao/judo/ver.blade.php
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/ver.blade.php
Aparentemente isso foi pedido por Rose, então estou fazendo...
> Adicionando o perfil do paciente em todas as avaliações/anamneses

- Saudox/app/AvaliacaoNeuropsicologica.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
- Saudox/resources/views/profissional/avaliacao/neuropsicologia/criar.blade.php
- Saudox/resources/views/profissional/avaliacao/neuropsicologia/ver.blade.php
- Tela de visualização da Avaliação neuropsicológica
- Ficou faltando ajustar dois campos onde vão ser exibidos arquivos
> [#174982702] Ver avaliação neuropsicologica

- Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
- Saudox/public/css/main.css
- Saudox/resources/views/profissional/anamnese/psicopedagogia/criar.blade.php
- Saudox/resources/views/profissional/anamnese/psicopedagogia/ver.blade.php
- Anamnese gigante pode ser vista por funcionários
* Já inclui as informações do perfil do paciente na página da anamnese
> [#175322770] Tela de visualização da anamnese gigante

- Saudox/.editorconfig
- Saudox/public/css/form_pag.css
- Saudox/public/css/main.css
- Saudox/public/css/refator.css
- Saudox/public/css/tabela.css
- Saudox/public/js/form_pag.js
- Saudox/public/js/tabela.js
- Saudox/tests/Feature/AnamneseFonoTest.php
- Saudox/tests/Feature/AnamnesePNPTest.php
- Saudox/tests/Feature/AnamneseTerapiaOTest.php
- Saudox/tests/Feature/AnamneseTest.php
- Saudox/tests/Feature/AvaliacaoJudoTest.php
- Saudox/tests/Feature/AvaliacaoNeuropsicologicaTest.php
- Saudox/tests/Feature/AvaliacaoTerapiaOTest.php
- Saudox/tests/Feature/AvaliacaoTest.php
- Saudox/tests/Feature/CadastroProfissionalTest.php
- Saudox/tests/Feature/EvolucaoTest.php
- Saudox/tests/Feature/LoginProfissionalTest.php
- Saudox/tests/Feature/PacienteHomeTest.php
- Saudox/tests/Unit/AdminControllerTest.php
- Saudox/tests/Unit/AnamneseFonoTest.php
- Saudox/tests/Unit/AnamneseTOTest.php
- Saudox/tests/Unit/AvaliacaoJudoTest.php
- Saudox/webpack.mix.js
Não é necessário revisar esse PR agora, apenas abri agora pra ver o progresso pelo codacy.
> PR apenas de ajustes do codacy

- Saudox/public/css/refator.css
- Saudox/resources/views/paciente/home.blade.php
- Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
- Saudox/resources/views/profissional/anamnese/terapia_ocupacional/ver.blade.php
- Saudox/resources/views/profissional/avaliacao/judo/ver.blade.php
- Saudox/resources/views/profissional/avaliacao/neuropsicologia/ver.blade.php
- Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/ver.blade.php
- Espaçamento das views
- Campos que extrapolam certos limites
- Tabela na avaliação de judô (ficou mais bonita e padronizada com o resto do projeto)
- Botões na home de paciente (alguem havia desconfigurado eles)
> Ajustes nas views de anamnese e avaliação (e na home de paciente rs)

- Saudox/composer.json
- Saudox/composer.lock
- Saudox/storage/debugbar/.gitignore
- Ferramenta muito útil para debugação (vai ajudar bastante a debugar os problemas nos testes).
Referência: https://github.com/barryvdh/laravel-debugbar
> Ferramenta: debugar

- Saudox/app/Http/Controllers/PacienteAvaliacaoController.php
- Saudox/public/css/main.css
- Saudox/public/css/refator.css
- Saudox/resources/views/paciente/anamneses/fono.blade.php
- Saudox/resources/views/paciente/anamneses/pnp.blade.php
- Saudox/resources/views/paciente/anamneses/tocp.blade.php
- Saudox/resources/views/paciente/avaliacoes/fono.blade.php
- Saudox/resources/views/paciente/avaliacoes/judo.blade.php
- Saudox/resources/views/paciente/avaliacoes/neuro.blade.php
- Saudox/resources/views/paciente/avaliacoes/terapia_ocupacional.blade.php
Mesma coisa que ontem... vou atualizando o PR pra saber como o codacy responde, quando acabar eu aviso.
> Mais ajustes que o codacy reclama

- Saudox/tests/CreatesApplication.php
- Saudox/tests/TestCase.php
- Agora é realizado umam limpeza em todo o cache o laravel antes de iniciar os testes.
---
Eu também dou uma limpada no cache do composer depois que dou composer install
> Resolução de bug com o cache do phpUnit + Laravel

- Saudox/tests/Feature/AnamnesePNPTest.php
- Saudox/tests/Feature/AvaliacaoNeuropsicologicaTest.php
- Teste de visualização de uma anamnese PNP já criada
- Teste de edição de avaliação Neuropsicológica
(eu errei no nome do commit da avaliação, troquei a palavra avaliação por anamnese)
---
[#174982702][#175322770]
> Testes: visualização de ana PNP + edição de ava neuro

- Saudox/tests/Feature/Paciente_AgendamentosTest.php
- Saudox/tests/Feature/Paciente_HomeTest.php
- Saudox/tests/Feature/Paciente_LoginTest.php
- Saudox/tests/Feature/Profissional_AgendamentosTest.php
- Saudox/tests/Feature/Profissional_AnamneseFonoTest.php
- Saudox/tests/Feature/Profissional_AnamnesePNPTest.php
- Saudox/tests/Feature/Profissional_AnamneseTerapiaOTest.php
- Saudox/tests/Feature/Profissional_AvaliacaoJudoTest.php
- Saudox/tests/Feature/Profissional_AvaliacaoNeuropsicologicaTest.php
- Saudox/tests/Feature/Profissional_AvaliacaoTerapiaOTest.php
- Saudox/tests/Feature/Profissional_CadastroClienteTest.php
- Saudox/tests/Feature/Profissional_CadastroProfissionalTest.php
- Saudox/tests/Feature/Profissional_LoginTest.php
- Alteração realizada para melhor organização dos testes.
__O que foi feito:__ Foram separados os testes que focaram no usuário Paciente, dos que focavam no usuário Profissional.
Baseando-se numa releitura dos feedbacks da professora.
> Organizando arquivos de teste, dividindo entre Paciente e Profissionais. [#175472150]

- Saudox/app/EvolucaoPsicologica.php
- Saudox/app/Http/Controllers/Profissional/ProfissionalEvolucaoController.php
- Saudox/database/seeds/EvolucaoPsicologicasAutSeeds.php
- Saudox/public/css/timeline.css
- Saudox/resources/views/profissional/evolucao/neuropsicologia/criar.blade.php
- Saudox/resources/views/profissional/evolucao/neuropsicologia/editar.blade.php
- Saudox/resources/views/profissional/evolucao/neuropsicologia/ver.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Saudox/routes/profissional/evolucao/neuropsicologia.php
- Timeline bonitona
- Ordenado por data (mais antigo mais em baixo)
- Links pros profissionais
- Métodos de pegar o model de profissional ou paciente pela evolução (facilitou na view de ver)
> Criação, edição e visualização de evoluções de neuropsicologia [#175305991] [#175306051] [#175306141]

- Saudox/app/Http/Controllers/AgendamentosController.php
- Saudox/app/Http/Controllers/PacienteController.php
- Saudox/app/Profissional.php
- Saudox/public/css/refator.css
- Saudox/public/js/main.js
- Saudox/resources/views/layouts/mainlayout.blade.php
- Saudox/resources/views/paciente/home.blade.php
- Saudox/resources/views/profissional/avaliacao/neuropsicologia/ver.blade.php
- Saudox/resources/views/profissional/home.blade.php
- Saudox/resources/views/profissional/recepcao/home.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
- Saudox/tests/Feature/Profissional_AgendamentosTest.php
_Conjunto de alterações menores, no entanto que são necessárias._
- Resolver atribuições trocadas das anamneses no controller que chama a home do paciente (as anamneses estavam trocadas)
- Restrições de acesso por meio de nível de permissão (por exemplo, nem todos os usuários podem criar agendamentos, etc)
- Seguindo a ideia do tópico anterior, também foi refatorado as permissões na home do paciente, visto por um profissional (por exmeplo, um fonoaudiólogo não poderá criar uma avaliação de judô)
- Deixar mais claro os campos que são obrigatórios (colocando em negrito). O contrate da cor vermelha com o fundo escuro deixar implícito
- E um conjunto de resoluções de má identação
> Melhorias Diversas 2 - Melhor descriço na descrição [#175472150]

- Saudox/app/Http/Controllers/AgendamentosController.php
- Saudox/database/seeds/EvolucaoJudoAutSeeds.php
- Saudox/database/seeds/EvolucaoPsicologicasAutSeeds.php
- Saudox/database/seeds/EvolucaoTerapiaOcupacionalsAutSeeds.php
- Saudox/resources/views/profissional/evolucao/neuropsicologia/criar.blade.php
- Saudox/resources/views/profissional/evolucao/neuropsicologia/editar.blade.php
- Saudox/resources/views/profissional/ver_paciente.blade.php
__De modo geral, são pequenas modificações que acabam sendo relevantes para o projeto.__
_O que foi feito:_
- Adicionar botão de editar paciente no perfil do mesmo (para profissional editar)
- Indicar quais campos são obrigatórios em Evolução Neuropsicológica
- Ajustes nas Seeds, a randomização está muito exagerada em diversos momentos. (diminuir o tamanho das orações na geração de texto automático)
> Melhorias Diversas 3 [#175490138]

- Saudox/resources/views/profissional/avaliacao/fonoaudiologia/criar.blade.php
- Todos os blocos de perguntas que faltavam (faltavam 10 blocos)
- Os commits explicam o que foi feito
> [#174990402] Finalização da view de criar da Avaliação de Fonoaudiologia

- Saudox/resources/views/profissional/avaliacao/fonoaudiologia/ver.blade.php
- A view segue o padrão da view de criação
- Todos os campos estão diretamente ligados com os campos de criação
> [#175447898] View de visualizar a avaliação de fonoaudiologia

- Saudox/public/js/ava_fono.js
- Saudox/resources/views/profissional/avaliacao/fonoaudiologia/ver.blade.php
- Setando o bloco correto na criação
- Adicionando Labels com o questionario que está sendo visto
> Ajustes minimos na view de ver a avalição de fonoaudiologia e bug na criação
